AWSTemplateFormatVersion: "2010-09-09"
Description: "Enya Application Infrastructure"

Parameters:

  EcsImageId:
    # TODO: Implement automatic update or notifications: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS-AMI-SubscribeTopic.html
    Description: Image ID for running the ECS Cluster instances
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

  EcsInstanceType:
    # https://aws.amazon.com/ec2/instance-types/
    # The types of instances is limited to avoid mistakes generating huge costs by putting the wrong instance type.
    Description: Type of instances to be added to the ECS cluster
    Type: String
    Default: c6i.4xlarge

  InfrastructureStackName:
    Description: Infrastructure stack to associate this stack with
    Type: String
    Default: infrastructure-core

Resources:

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"

  LoadBalancerIntSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG for ${AWS::StackName} Internal LB"
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      SecurityGroupIngress:
      - Description: Allow all outbound traffic
        IpProtocol: "-1"
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IntLB"

  LoadBalancerGraph:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: dualstack
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '3600'
      Type: application
      SecurityGroups:
        - !Ref LoadBalancerIntSecurityGroup
      Subnets:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet2

  LoadBalancerReplicaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG for ${AWS::StackName} Replica LB"
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      SecurityGroupIngress:
      - Description: Allow all outbound traffic
        IpProtocol: "-1"
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Replica-LB"

  LoadBalancerReplicaDTL:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Type: network
      Subnets:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PrivateSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PrivateSubnet2

  LoadBalancerReplica:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: network
      Subnets:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet2

  LoadBalancerBlockscout:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Subnets:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet2
      Type: network

  LoadBalancerProxyd:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: dualstack
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '3600'
      Type: application
      SecurityGroups:
        - !Ref LoadBalancerIntSecurityGroup
      Subnets:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PublicSubnet2

  EcsCluster:
    Type: AWS::ECS::Cluster

  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [!Sub "ec2.${AWS::URLSuffix}"]
          Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: AllowAccessToELB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:*"
                  - "ec2:Describe*"
                  - "s3:*"
                  - "elasticloadbalancing:*"
                  - "elasticloadbalancing:Describe*"
                  - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
                  - "elasticloadbalancing:DeregisterTargets"
                  - "elasticloadbalancing:DescribeTargetGroups"
                  - "elasticloadbalancing:DescribeTargetHealth"
                  - "elasticloadbalancing:RegisterTargets"
                  - "elasticfilesystem:ClientMount"
                  - "elasticfilesystem:ClientRootAccess"
                  - "elasticfilesystem:ClientWrite"
                  - "elasticfilesystem:DescribeMountTargets"
                Resource: "*"

  EcsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EcsInstanceRole]

  EcsSecurityGroupReplica:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG for ${AWS::StackName} Landscape ECS Cluster Replica"
      VpcId:
        Fn::ImportValue: !Sub ${InfrastructureStackName}:VpcId
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref LoadBalancerReplicaSecurityGroup
        IpProtocol: tcp
        FromPort: 22
        ToPort: 65535
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Replica-ECS-Cluster"

  EcsLaunchConfigurationReplica:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            '/etc/ecs/ecs.config':
              content: !Sub |
                ECS_CLUSTER=${EcsCluster}
                ECS_ENABLE_TASK_IAM_ROLE=true
                ECS_CONTAINER_STOP_TIMEOUT=5s
              mode: "000644"
              owner: root
              group: root
    Properties:
      InstanceType: !Ref EcsInstanceType
      SecurityGroups:
      - !Ref EcsSecurityGroupReplica
      IamInstanceProfile: !Ref EcsInstanceProfile
      ImageId: !Ref EcsImageId
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -ex
            yum -y install aws-cfn-bootstrap amazon-ssm-agent amazon-efs-utils
            systemctl enable --now amazon-ssm-agent
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbEgniumTWAjZjw7vgcMCrHALO7KcjXHo3I09ulp7ufd1jpk/0PCAPwRqURLZWujjkB/OGto8W/YqCF7F5s3VJvC5lq0Sbbmagyz7obTYRVBNA656wdw2T6udHoci26kQEJoEZCHjlnCnPnNC1IkiJMwjbXivcVdUeCuFaUREWqOB5qPDEoG3xfKqHF1qlVhuuI/Q14AsgUGtMNKQyuR97k/pL2KncTTIg1Ev2pMm3/4sND5TFtX907LNEz1fu1JQqpM/fXUM/a+rlREaBj+2+nWC37+TFjd3WWvohdMEljRGH8JnTcYU5hvfdZV62pLgNjz0LPAn+tLugwacbGy6J chenboyuan@Macbook.hsd1.va.comcast.net" > /home/ec2-user/.ssh/authorized_keys
            mkdir -p /mnt/efs /mnt/efs/db
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EcsLaunchConfigurationReplica --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroupReplica --region ${AWS::Region} || true

  AutoScalingGroupReplica:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref EcsLaunchConfigurationReplica
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupTotalInstances
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PrivateSubnet1
      - Fn::ImportValue: !Sub ${InfrastructureStackName}:PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Replica-ECS"
          PropagateAtLaunch: true
Outputs:
  EcsCluster:
    Value: !Ref EcsCluster
    Export:
      Name: !Sub "${InfrastructureStackName}:EcsClusterReplica"
  EcsSecurityGroup:
    Value: !Ref EcsSecurityGroupReplica
    Export:
      Name: !Sub "${InfrastructureStackName}:EcsSecurityGroupReplica"
  LoadBalancerReplicaDNSName:
    Value: !GetAtt LoadBalancerReplica.DNSName
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerReplica:DNSName"
  LoadBalancerReplicaArn:
    Value: !Ref LoadBalancerReplica
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerReplica:ARN"
  EFSFilesystem:
    Value: !Ref FileSystem
    Export:
      Name: !Sub "${InfrastructureStackName}:EFSFilesystemReplica"
  LoadBalancerReplicaSecurityGroup:
    Value: !Ref LoadBalancerReplicaSecurityGroup
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerReplica:SecurityGroup"
  LoadBalancerReplicaDTLDNSName:
    Value: !GetAtt LoadBalancerReplicaDTL.DNSName
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerReplicaDTL:DNSName"
  LoadBalancerReplicaDTLArn:
    Value: !Ref LoadBalancerReplicaDTL
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerReplicaDTL:ARN"
  LoadBalancerBlockscoutDNSName:
    Value: !GetAtt LoadBalancerBlockscout.DNSName
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerBlockscout:DNSName"
  LoadBalancerBlockscoutArn:
    Value: !Ref LoadBalancerBlockscout
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerBlockscout:ARN"
  LoadBalancerGraphDNSName:
    Value: !GetAtt LoadBalancerGraph.DNSName
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerGraph:DNSName"
  LoadBalancerGraphArn:
    Value: !Ref LoadBalancerGraph
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerGraph:ARN"
  LoadBalancerProxydDNSName:
    Value: !GetAtt LoadBalancerProxyd.DNSName
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerProxyd:DNSName"
  LoadBalancerProxydArn:
    Value: !Ref LoadBalancerProxyd
    Export:
      Name: !Sub "${InfrastructureStackName}:LoadBalancerProxyd:ARN"
