AWSTemplateFormatVersion: "2010-09-09"
Description: "Enya Graph Application Deployment"

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  ServiceCount:
    Type: Number
    Default: 1

  ImageTag:
    Type: String
    Default: push2aws

  DockerPrefix:
    Type: String
    Default: omgx

  ECRRegistry:
    Type: String
    Default: 942431445534.dkr.ecr.us-east-1.amazonaws.com

  InfrastructureStackName:
    Description: Infrastructure stack to associate this stack with
    Type: String
    Default: infrastructure-coredev

  SecretName:
    Description: AWS Secret Name used for the service
    Type: String
    Default: integration-v2

Conditions:
  IsProduction:
    !Equals [!Ref EnvironmentName, "production"]

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub ecs-tasks.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowAccessToSecrets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetResourcePolicy"
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecretVersionIds"
                Resource:
                  - arn:aws:secretsmanager:us-east-1:942431445534:secret:*
        - PolicyName: AllowAccessToELB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:Describe*"
                  - "elasticloadbalancing:*"
                  - "elasticloadbalancing:Describe*"
                  - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
                  - "elasticloadbalancing:DeregisterTargets"
                  - "elasticloadbalancing:DescribeTargetGroups"
                  - "elasticloadbalancing:DescribeTargetHealth"
                  - "elasticloadbalancing:RegisterTargets"
                  - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
                Resource: "*"

  DNSRecordV4Graph:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      AliasTarget:
        DNSName:
          Fn::Sub:
            - "dualstack.${DomainName}."
            - DomainName:
                Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerGraph:DNSName"
        HostedZoneId:
          Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancer:CanonicalHostedZoneID"
      HostedZoneName:
        Fn::Sub:
          - "${DomainName}."
          - DomainName:
              Fn::ImportValue: !Sub "${InfrastructureStackName}:DomainName"
      Name:
        Fn::Sub:
          - "graph.${DomainName}."
          - DomainName:
              Fn::ImportValue: !Sub "${InfrastructureStackName}:DomainName"

  GraphLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8000
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  GraphListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerGraph:ARN"
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01 # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
      Certificates:
      - CertificateArn: arn:aws:acm:us-east-1:942431445534:certificate/7488423e-1d39-4fd3-9422-bf9a80fa7e28
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref GraphLBTargetGroup

  GraphLBTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8001
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  GraphListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerGraph:ARN"
      Port: 8001
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01 # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
      Certificates:
      - CertificateArn: arn:aws:acm:us-east-1:942431445534:certificate/7488423e-1d39-4fd3-9422-bf9a80fa7e28
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref GraphLBTargetGroup1

  GraphLBTargetGroup3:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8030
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  GraphListener3:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerGraph:ARN"
      Port: 8030
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01 # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
      Certificates:
      - CertificateArn: arn:aws:acm:us-east-1:942431445534:certificate/11a60189-ef87-47ad-af76-802039495816
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref GraphLBTargetGroup3

  GraphLBTargetGroup4:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8040
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  GraphListener4:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerGraph:ARN"
      Port: 8040
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01 # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
      Certificates:
      - CertificateArn: arn:aws:acm:us-east-1:942431445534:certificate/11a60189-ef87-47ad-af76-802039495816
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref GraphLBTargetGroup4

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: ipfs
          Host:
            SourcePath: "/mnt/efs/ipfs"
      ContainerDefinitions:
        - Image: ipfs/go-ipfs:v0.4.23
          Name: ipfs
          PortMappings:
            - ContainerPort: 5001
              HostPort: 0
          MountPoints:
            - ContainerPath: "/data/ipfs"
              SourceVolume: ipfs
          DockerLabels:
            com.datadoghq.ad.check_names: '["ipfs"]'
            com.datadoghq.ad.init_configs: '[{}]'
            com.datadoghq.ad.logs: '[{"source": "ipfs", "service": "ipfs"}]'
          Essential: true
          Memory: "64"
        - Image: 942431445534.dkr.ecr.us-east-1.amazonaws.com/omgx/graph:latest
          Name: graph
          Ulimits:
            - Name: core
              SoftLimit: 0
              HardLimit: 0
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
            - ContainerPort: 8001
              HostPort: 8001
            - ContainerPort: 8030
              HostPort: 8030
            - ContainerPort: 8040
              HostPort: 8040
          EnvironmentFiles:
            - Value: !Sub
              - "arn:aws:s3:::${S3Bucket}/graph.env"
              - S3Bucket:
                  Fn::ImportValue: !Sub "${InfrastructureStackName}:S3Bucket"
            - Type: "s3"
          DockerLabels:
            com.datadoghq.ad.check_names: '["graph"]'
            com.datadoghq.ad.init_configs: '[{}]'
            com.datadoghq.ad.logs: '[{"source": "graph", "service": "graph"}]'
          Essential: true
          Memory: "64"
          Links:
            - ipfs
      NetworkMode: host
      TaskRoleArn: !GetAtt TaskRole.Arn
      Family: !Sub "Graph-${EnvironmentName}"
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:EcsClusterReplica"
      LoadBalancers:
        - ContainerName: graph
          ContainerPort: 8000
          TargetGroupArn: !Ref GraphLBTargetGroup
        - ContainerName: graph
          ContainerPort: 8001
          TargetGroupArn: !Ref GraphLBTargetGroup1
        - ContainerName: graph
          ContainerPort: 8030
          TargetGroupArn: !Ref GraphLBTargetGroup3
        - ContainerName: graph
          ContainerPort: 8040
          TargetGroupArn: !Ref GraphLBTargetGroup4
      DesiredCount: !Ref ServiceCount
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      ServiceName: "graph"
      TaskDefinition: !Ref TaskDefinition
