AWSTemplateFormatVersion: "2010-09-09"
Description: "Enya Data Transport Layer Application Deployment"

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  CFHelperELBv2RulePriorityStack:
    Type: String
    Default: CF-Helper-ELBv2-Rule-Priority

  ServiceCount:
    Type: Number
    Default: 1

  ImageTag:
    Type: String
    Default: push2aws

  DataTransportLayerImage:
    Type: String
    Default: data-transport-layer

  DockerPrefix:
    Type: String
    Default: omgx

  ECRRegistry:
    Type: String
    Default: hub.docker.com

  InfrastructureStackName:
    Description: Infrastructure stack to associate this stack with
    Type: String
    Default: infrastructure-coredev

  SecretName:
    Description: AWS Secret Name used for the service
    Type: String

Conditions:
  IsProduction:
    !Equals [!Ref EnvironmentName, "production"]

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub ecs-tasks.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowAccessToS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetBucketLocation"
                Resource: !Sub
                    - "arn:aws:s3:::${S3BucketV2}/replica-dtl.env"
                    - S3BucketV2:
                        Fn::ImportValue: !Sub "${InfrastructureStackName}:S3BucketV2"

  DataTransportLayerReplicaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerReplica:ARN"
      Port: 7878
      Protocol: TCP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DataTransportLayerReplicaLBTargetGroup

  DataTransportLayerReplicaListener2:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerReplica:ARN"
      Port: 8081
      Protocol: TCP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref DataTransportLayerDeployerReplicaLBTargetGroup1

  DataTransportLayerReplicaLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  DataTransportLayerDeployerReplicaLBTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8081
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:VpcId"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      TargetType: "instance"

  DataTransportLayerDeployerReplicaLBListenerRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref DataTransportLayerDeployerReplicaLBTargetGroup1
      ListenerArn: !Ref DataTransportLayerReplicaListener2

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: db
          Host:
            SourcePath: "/mnt/efs/replica_dtl/db"
      ContainerDefinitions:
        - Image: !Sub "${DockerPrefix}/${DataTransportLayerImage}:${ImageTag}"
          Name: data_transport_layer
          PortMappings:
            - ContainerPort: 7878
              HostPort: 7878
            - ContainerPort: 8081
              HostPort: 8081
          EnvironmentFile:
            - Value: !Sub
              - "arn:aws:s3:::${S3BucketV2}/replica-dtl.env"
              - S3BucketV2:
                  Fn::ImportValue: !Sub "${InfrastructureStackName}:S3BucketV2"
            - Type: "s3"
          Environment:
            - Name: DATA_TRANSPORT_LAYER__SYNC_FROM_L1
              Value: true
            - Name: DATA_TRANSPORT_LAYER__SYNC_FROM_L2
              Value: true
            - Name: DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT
              Value: !Sub
                - "https://${EndpointAddress}/"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:DomainName"
            - Name: DEPLOYER_HTTP
              Value: !Sub
                - "https://${EndpointAddress}:8081"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerDeployer"
            - Name: URL
              Value: !Sub
                - "https://${EndpointAddress}:8081/addresses.json"
                - EndpointAddress:
                    Fn::ImportValue: !Sub "${InfrastructureStackName}:LoadBalancerDeployer"
          MountPoints:
            - ContainerPath: "/db"
              SourceVolume: db
          DockerLabels:
            com.datadoghq.ad.check_names: '["replica_dtl"]'
            com.datadoghq.ad.init_configs: '[{}]'
            com.datadoghq.ad.logs: '[{"source": "replica_dtl", "service": "replica_dtl"}]'
          Essential: true
          Memory: "256"
      NetworkMode: host
      ExecutionRoleArn: "arn:aws:iam::942431445534:role/ecs-s3-rolw"
      TaskRoleArn: !GetAtt TaskRole.Arn
      Family: !Sub "Replica-DTL-${EnvironmentName}"
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${InfrastructureStackName}:EcsClusterReplica"
      LoadBalancers:
        - ContainerName: data_transport_layer
          ContainerPort: 7878
          TargetGroupArn: !Ref DataTransportLayerReplicaLBTargetGroup
        - ContainerName: data_transport_layer
          ContainerPort: 8081
          TargetGroupArn: !Ref DataTransportLayerDeployerReplicaLBTargetGroup1
      DesiredCount: !Ref ServiceCount
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      ServiceName: "replica-dtl"
      TaskDefinition: !Ref TaskDefinition
